sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - sudo apt-get update -qq
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g web-component-tester
  - npm install -g bower
  - bower install
script:
  - wct --skip-plugin sauce --plugin local -l chrome
